docs/source/daq_basic.rst
docs/source/daq_config.rst
docs/source/plans_basic.rst
pcdsdaq/daq.py
tests/test_daq.py

- Add `Daq.record` as a property to schedule a `Daq.configure(record=True)` call later.
- Fix issue where `record` would be reset to `False` after every `configure` where we forget to set it.
This makes it so we can enable/disable recording without seeing the output of `Daq.configure` in `ipython`. The fix means we can create plans that ignore the `record` parameter and leave it to the user to set up.

ENH: Record property and doc updates

---

pcdsdaq/daq.py
tests/test_daq.py

This warning fires every time we import `daq.py`, even if it's an incidental import that doesn't make a `Daq` object. I think this warning is important, but I don't think it should run on import.
An interesting side effect is that we don't get the warning if we've acknowledged the lack of `pydaq` by setting up the sim daq.

FIX: move warning to class instantiation

---

pcdsdaq/daq.py
tests/test_daq.py

Allow `daq.begin(record=True)` to temporarily set record to `True` for a run
Mark Hunter asked for this and it seemed reasonable
closes #15 
Passes tests, needs to be verified with real hardware
Added to docstring only, should make a note in the examples too
- Will not merge until discussing more, not a bugfix and not urgent
- Need to handle edge case:
```
daq.begin(duration=5, record=True, wait=True)
daq.begin(duration=5, wait=True)
```
This will try to reconfigure back to `record=False` in the middle of an open run, which is not allowed. This should either be stated in the docs or protected for by the class. I might even go as far to say we add a `end_run=True` argument option here... To make it simpler for the user to use `begin` as a one-stop-shop for doing a daq run without a …

ENH: Record in Begin

---

docs/source/releases.rst
pcdsdaq/daq.py
tests/test_daq.py

A user can escape `daq.begin(wait=True)` using `ctrl+c`, which will stop the run.
Previously, this did not stop the run, which caused confusion because the run was still going and another run could not be started.
closes #20 
Added tests and tested in `sxr`
Edited docstrings and added to release notes.

ENH: Stop begin(wait=True) on ctrl+c

---

docs/source/daq_basic.rst
docs/source/daq_config.rst
docs/source/plans_basic.rst
docs/source/releases.rst
pcdsdaq/daq.py
pcdsdaq/sim/pydaq.py
tests/test_daq.py

Mishmash of ideas I implemented on the plane, not quite ready to merge but good for discussion:
- Resume previous state after a bluesky run via `stage` and `unstage` (idea: should this be put on `begin` as well?). This means that if we were disconnected, we disconnect after a run, if we were running we start an infinite run (with record forced to `False`), etc.
- Queue up configurations without executing them via `preconfig`. This makes it possible to take advantage of the previous point from a disconnected state. This also allows the user to avoid seeing the giant return `dict` from `configure` that people will find annoying.
- `begin_infinite` helper function to run the `daq` forever. It was tough to manually do this after a configure without special knowledge, so this helps you set it …

ENH: QOL improvements from the flight back

---

docs/source/index.rst
docs/source/misc.rst
docs/source/releases.rst
pcdsdaq/daq.py
pcdsdaq/ext_scripts.py
pcdsdaq/sim/__init__.py
pcdsdaq/sim/pydaq.py
tests/conftest.py
tests/test_daq.py
tests/test_ext_scripts.py
tests/test_scan_vars.py

`daq.run_number()` gives the run number. It uses the `engineering_tools` scripts to accomplish this.
The `pydaq` run number utilities are only valid if we just did a run. These scripts use regdb to get the real run number. I did not want to open the can of worms of getting regdb into our environment, though it may not have been hard.
closes #22 
I've added tests and I've done some live testing.
I added a `misc.rst` page to the docs.

ENH: Run number

---

.travis.yml
conda-recipe/pre-unlink.sh
pcdsdaq/pydaq_links/unlinker

Add a `pre-unlink` script to the conda recipe
`conda install pcdsdaq=<newer_version>` fails because I have a post-link script but no pre-unlink script
Sort of tested in the travis I think? Looking for suggestions

FIX: attempt to fix unlink reinstall bug

---

docs/source/plans_basic.rst
pcdsdaq/daq.py
tests/conftest.py
tests/test_daq.py

Some changes that make it easy to run the daq "forever" while waiting for everything else to complete e.g. the sequencer, some slow detectors, some averaging things, etc.
Usage would be something like `yield from configure(daq, events=0), yield from scan([daq, ...], ...)`
- Switch wait to throw an error when daq is set to run forever as a safeguard
- Clarify the trigger error is for an unconfigured daq, rather than an infinitely-configured daq
- Stop on the read
- If configured to run forever, then `_get_end_status` returns a finished status immediately
When you have the daq and the sequencer together in a scan it does something like:
- `daq.trigger()`
- `seq.trigger()`
- wait for everything to be done
- `daq.read()`
- `seq.read()`
So if daq's trigger status returns done immediately we …

ENH: Allow daq to be used in "run until other things are done" mode

---

docs/source/daq_basic.rst
pcdsdaq/daq.py

Add a configurable sleep time for the `Daq` class to wait after the DAQ has said that it is ready to go.
In some DAQ configurations, the DAQ says that it's ready long before it really is. This is a feature to compensate for this.
closes #41 
It passes the existing tests and confirmed working in my session.
Some lines added to docstrings and docs.

ENH: begin wait

---

conda-recipe/meta.yaml
docs/source/daq_basic.rst
pcdsdaq/daq.py
tests/conftest.py
tests/test_ami.py
tests/test_daq.py

Force the `Daq` class to wait at least `1s` between `stop` and `begin`. The timer starts on `stop`, and the sleep is skipped if enough other things have happened.
closes #40 
Also fix an unrelated bug where the `Daq` class wasn't correctly reset after a `disconnect`, and finally kill the deprecated argument.
I also redid some of the `ami` tests because they stopped working and the old tests didn't make sense to me any more.
Doing scans where there is very little going on between steps (e.g. no moves or really fast moves) AND there is enough during the step (`>0.05s` of action) results in `pydaq.Control.stop` routines that exit quickly but don't actually stop the daq in that time. Calling `pydaq.Control.begin` in this approx `0.45s` window when the `DAQ` claims to be ready to run causes …

FIX: Rapid cycle bug

---

.travis.yml
pcdsdaq/ext_scripts.py

- Add a py37 build to the travis that is allowed to fail. It will fail until the dependencies allow py37.
Bored on a friday night

CI: add py37

---

pcdsdaq/daq.py

Newer bluesky validators do not accept `None` as a data shape in the descriptors. The correct API is now to pass an empty array.

FIX: None is no longer a valid data shape

---

pcdsdaq/daq.py
pcdsdaq/ext_scripts.py

This PR fixes a race condition in `Daq.begin` that would cause failed starts when the external scripts we call get slow. There was an assumption that the timeout for `begin` would only account for `pydaq` time, but this is not the case.
Now we have separate timeouts for `begin` and for the external scripts.
#65 
Locally with the real DAQ, hopefully the tests still pass
This will be in the notes for the next release.

BUG: Begin timeout

---

pcdsdaq/ami.py
pcdsdaq/daq.py
pcdsdaq/ext_scripts.py

- Change bykik code to `False` by default in `set_filter` as per Silke's instructions
- Give up on the run_number getter on the first failure per session, it is merely cosmetic and should not slow down the scan.
- Decrease the get run number timeout to 1s.
- Copy the good docstring for `set_filter` over to the daq method
- Increase timeouts for get_hutch and get_ami_proxy, then cache the result. The result does not change.
- Various changes requested between shifts
- closes #72

ENH: Various updates for Better Ops

---

pcdsdaq/daq.py
pcdsdaq/sim/pydaq.py

- When doing our value stuffing of the controls arg to pass to pydaq, add a step where we get the first element of the motor position if it was a tuple, list or similar.
- Add a failure state to the sim pydaq based on #77 for testing.
closes #77 
PseudoPositioners have position attributes that are named tuples. The first element in the tuple is the most important, and therefore the one most likely to be sought after if the user passes in the entire pseudopositioner. Therefore, taking the first element to report to the DAQ will be sufficient for this use case.
Locally with the sim pydaq
Not yet

MNT: Allow Controls Arg to Accept PseudoPositioners

---

pcdsdaq/daq.py

- Allow "tri-state" configuration args (True, False, None), and allow the Daq class to know whether the user has passed in `None` versus not passed in anything at all
- Allow `record=None` to mean "Use the record option selected in the DAQ GUI"
- Update docstrings
- Allowing us to run using the record option in the GUI is a feature of pydaq that was not exposed well here, and seemed to work only some of the time- though reading the code, it's not clear if it ever worked.
- Using a non-None sentinel is the easiest way to allow the user to pass in `None` as a functional value rather than as a "nobody passed anything" default. Some of the arguments (events, duration, record, controls) have special meanings for `None`, and should also not update themselves if someone configures a different …

REF: Fix issues with "use the DAQ GUI" record option, refactor configure args in general.

---

pcdsdaq/ami.py
pcdsdaq/daq.py
pcdsdaq/ext_scripts.py
pcdsdaq/sim/__init__.py
pcdsdaq/sim/pydaq.py
tests/test_ami.py
tests/test_daq.py
tests/test_ext_scripts.py

- Add `hutch_name` as an argument to the `Daq` class to skip calling the `get_hutch_name` external script
- Rename `hutch_name()` to `get_hutch_name()` for clarity
- `get_hutch_name()` can be slow and we know what hutch we're in before calling it
- closes #76 
- Basic coverage test added
- Docstrings

ENH: Allow hutch to be passed into DAQ instead of using scripts

---

pcdsdaq/daq.py
tests/test_daq.py

Remove the "disconnect if we weren't connected" clause, this was taking the "return to previous state" mantra too far.
This closes the open DAQ/AMI plots, which the scientists would have liked to keep looking at after a run.
N/A, maybe this even breaks the test suite idk
N/A

MNT: do not disconnect the DAQ in unstage ever, as this is disruptive

---

.travis.yml
pcdsdaq/scan_vars.py
tests/conftest.py
tests/test_scan_vars.py

Add scan PV handling for the following plan patterns:
- `outer_product` (`grid_scan`)
- `inner_list_product` (`list_scan`)
- `outer_list_product` (`list_grid_scan`)
Previously, we were only handling `inner_product` (`scan`)
This should make things like `delay_scan` properly show themselves in the scan tables as per reading the metadata at https://github.com/pcdshub/nabs/blob/06d21428cddaa3f2ec6a31150f9d4758f5a7c2c5/nabs/plans.py#L92-L103, as well as cover all the most common scan cases.
This does not cover more exotic shapes like spirals, etc., but it does lay the groundwork for handling more exotic patterns.
https://jira.slac.stanford.edu/browse/LCLSECSD-740
https://jira.slac.stanford.edu/browse/LCLSECSD-1069
These scan variables in old python were simply written to during the normal …

ENH/FIX: fill in scan PVs properly from most normal scan types

---

pcdsdaq/daq/__init__.py
pcdsdaq/daq/interface.py
pcdsdaq/daq/lcls1.py
pcdsdaq/daq/lcls2.py
pcdsdaq/daq/original.py
pcdsdaq/exceptions.py
pcdsdaq/tests/test_daq_lcls2.py
pcdsdaq/tests/test_daq_original.py

Move all daq exceptions into a central `pcdsdaq.exceptions` for easy importability/discoverability/etc.
Closes #125 
Back-compat for exception imports was not retained as this is a newer structure
However this can be rectified easily if it seems worthwhile
Test suite on CI
Issue and PR text

MNT: consolidate exceptions and some relative imports

---

conda-recipe/meta.yaml
docs-requirements.txt
requirements.txt

pcdsutils is imported but not listed in the requirements
https://github.com/pcdshub/pcdsdaq/blob/22ad154ead6fd2676bb1589dca9b980e195d6661/pcdsdaq/daq/lcls2.py#L59
Found while trying to update the nabs dependencies
CI hopefully
This PR

BLD: include pcdsutils dependency

---

conda-recipe/meta.yaml
requirements.txt

- unpins numpy and bluesky, compatibility work has been completed
I dream of numpy 2, py 3.12 
CI 
This PR

BLD: unpin numpy, bluesky is npy2 compatible
